### ISSUE TITLE
How do you manage your  secrets?

### ISSUE THREAD

**Issue by pinpox** [barrucadu/nixfiles#3]
Hey, sorry didn't know where else to ask this:

Your config is very interesting, I'm setting up my first nix boxes. How do you manage your secrets?
I've got my `configuration.nix` mostly done, but don't understand how or where to store secrets so they can by synced (Things like  private keys, passwords, app credentials...) Could you share a (redacted) version of your secret files?

Also, how do you put them on a new install, just copy? syncthing?
For reference, I mean the files specified in lines like these:
https://github.com/barrucadu/nixfiles/blob/e205589e33ee35c7589233b9636c42eb0688b49e/hosts/lainonlife/configuration.nix#L8

**Comment by barrucadu** [comment]
I've got a private git repository for secrets, which I clone to my ~, and then I symlink `/home/barrucadu/secrets/nixos/$(hostname)` to `/etc/nixos/secrets`.  It works, but the secrets are visible in the Nix store, which may or may not be good enough for your use-case.

I know there's been much thought on how nix / nixos could be changed to make secrets management better, but I don't think anything's been implemented yet.

I used to use `import` for all my secrets, and the secrets files just looked like this:

```nix
"secret value goes here"
```

But then I discovered `lib.fileContents`, so now I mostly just use that instead.

**Comment by pinpox** [comment]
Hey, thanks for the hints! Yeah I'm looking mainly for a solution that doesn't put everything in the nix store. For now, I have just put the files in /secrets and have apps that need access to it read from there. I think that should prevent it from landing in the store
